name: dlna_player
description: A DLNA Audio Player made with Flutter.

publish_to: 'none'

version: 1.0.0+31

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  xml: ^6.2.2
  upnp2: ^3.0.10
  audioplayers: ^6.0.0
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.1.0
  intl: ^0.20.2
  theme_provider: ^0.6.0
  package_info_plus: ^9.0.0
  window_manager: ^0.5.0
  beautiful_soup_dart: ^0.3.0
  http: ^1.2.0
  url_launcher: ^6.3.1
  hid_listener:
    path: ../hid_listener_fork
  dbus: ^0.7.10
  event_bus: ^2.0.1
  fuzzywuzzy: ^1.2.0
  form_validator: ^2.1.1
  async: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.0

flutter:
  generate: true # needed for i18n generation
  uses-material-design: true
  assets:
    - assets/images/

icons_launcher:
  image_path: 'assets/logo.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    linux:
      enable: true
    web:
      enable: true
      favicon_path: 'assets/favicon.png'
    macos:
      enable: true
    windows:
      enable: true
